Fix Cargo-rdme
Cargo-rdme 2 add added the ability to use interlinks and since CI is using the latest version (unpinned) it tries to generate them without the required toolchain:

```
Run cargo rdme --check
error: failed to transform intralinks: rust toolchain not installed: nightly-2026-06-22

`cargo-rdme` needs nightly-2026-06-22 to do intralink resolution. To install it run:

    rustup toolchain install nightly-2026-06-22

or, equivalently, run `cargo rdme install-rust-toolchain-for-intralinks`.
```